# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CTC_Track_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrackView(object):
    def setupUi(self, TrackView):
        TrackView.setObjectName("TrackView")
        TrackView.resize(981, 731)
        self.centralwidget = QtWidgets.QWidget(TrackView)
        self.centralwidget.setObjectName("centralwidget")
        self.sys_time_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.sys_time_label_2.setGeometry(QtCore.QRect(710, 10, 83, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sys_time_label_2.setFont(font)
        self.sys_time_label_2.setStyleSheet("border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.sys_time_label_2.setObjectName("sys_time_label_2")
        self.title_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.title_label_2.setGeometry(QtCore.QRect(0, 0, 981, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title_label_2.setFont(font)
        self.title_label_2.setAutoFillBackground(False)
        self.title_label_2.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"border: 3px solid black;")
        self.title_label_2.setObjectName("title_label_2")
        self.system_speed_spnbx_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.system_speed_spnbx_2.setGeometry(QtCore.QRect(910, 14, 62, 22))
        self.system_speed_spnbx_2.setObjectName("system_speed_spnbx_2")
        self.system_speed_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.system_speed_label_2.setGeometry(QtCore.QRect(806, 10, 169, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.system_speed_label_2.setFont(font)
        self.system_speed_label_2.setAutoFillBackground(False)
        self.system_speed_label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.system_speed_label_2.setObjectName("system_speed_label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 630, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 60, 71, 51))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(40, 110, 111, 131))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 10, 81, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(670, 60, 301, 91))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(670, 150, 301, 241))
        self.textEdit_4.setObjectName("textEdit_4")
        self.occupiedBlocks = QtWidgets.QScrollArea(self.centralwidget)
        self.occupiedBlocks.setGeometry(QtCore.QRect(669, 419, 301, 261))
        self.occupiedBlocks.setWidgetResizable(True)
        self.occupiedBlocks.setObjectName("occupiedBlocks")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 299, 259))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.occupiedBlocks.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 580, 91, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(170, 61, 481, 621))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 110, 31, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 31, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 170, 31, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 31, 31))
        self.label_4.setObjectName("label_4")
        self.title_label_2.raise_()
        self.system_speed_label_2.raise_()
        self.sys_time_label_2.raise_()
        self.system_speed_spnbx_2.raise_()
        self.pushButton.raise_()
        self.textEdit.raise_()
        self.textEdit_2.raise_()
        self.pushButton_2.raise_()
        self.textEdit_3.raise_()
        self.textEdit_4.raise_()
        self.occupiedBlocks.raise_()
        self.pushButton_3.raise_()
        self.graphicsView.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        TrackView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TrackView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 21))
        self.menubar.setObjectName("menubar")
        TrackView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TrackView)
        self.statusbar.setObjectName("statusbar")
        TrackView.setStatusBar(self.statusbar)

        self.retranslateUi(TrackView)
        QtCore.QMetaObject.connectSlotsByName(TrackView)

    def retranslateUi(self, TrackView):
        _translate = QtCore.QCoreApplication.translate
        TrackView.setWindowTitle(_translate("TrackView", "MainWindow"))
        self.sys_time_label_2.setText(_translate("TrackView", "13:24:55"))
        self.title_label_2.setText(_translate("TrackView", "Track View"))
        self.system_speed_label_2.setText(_translate("TrackView", " System Speed"))
        self.pushButton.setText(_translate("TrackView", "Train View"))
        self.textEdit.setHtml(_translate("TrackView", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Key</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("TrackView", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Stations</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Trains</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Track</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Closure</span></p></body></html>"))
        self.pushButton_2.setText(_translate("TrackView", "TESTBENCH"))
        self.textEdit_3.setHtml(_translate("TrackView", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Select an element to view info</span></p></body></html>"))
        self.textEdit_4.setHtml(_translate("TrackView", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">info info blah blah</span></p></body></html>"))
        self.pushButton_3.setText(_translate("TrackView", "Import Map"))
        self.label.setText(_translate("TrackView", "<html><head/><body><p><img src=\":/KeyIcons/CTC_resources/station_small.png\"/></p></body></html>"))
        self.label_2.setText(_translate("TrackView", "<html><head/><body><p><img src=\":/KeyIcons/CTC_resources/train_small.png\"/></p></body></html>"))
        self.label_3.setText(_translate("TrackView", "<html><head/><body><p><img src=\":/KeyIcons/CTC_resources/track_line.png\"/></p></body></html>"))
        self.label_4.setText(_translate("TrackView", "<html><head/><body><p><img src=\":/KeyIcons/CTC_resources/closed_small.png\"/></p></body></html>"))
import CTC_track_resource_file


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TrackView = QtWidgets.QMainWindow()
    ui = Ui_TrackView()
    ui.setupUi(TrackView)
    TrackView.show()
    sys.exit(app.exec_())
