# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui_Of_Guis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Gui_of_guis(object):
    def setupUi(self, Gui_of_guis):
        Gui_of_guis.setObjectName("Gui_of_guis")
        Gui_of_guis.resize(302, 480)
        self.centralwidget = QtWidgets.QWidget(Gui_of_guis)
        self.centralwidget.setObjectName("centralwidget")
        self.CTC_open_Ui = QtWidgets.QPushButton(self.centralwidget)
        self.CTC_open_Ui.setGeometry(QtCore.QRect(10, 60, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.CTC_open_Ui.setFont(font)
        self.CTC_open_Ui.setObjectName("CTC_open_Ui")
        self.Track_controller_sw_open_ui = QtWidgets.QPushButton(self.centralwidget)
        self.Track_controller_sw_open_ui.setGeometry(QtCore.QRect(10, 200, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Track_controller_sw_open_ui.setFont(font)
        self.Track_controller_sw_open_ui.setObjectName("Track_controller_sw_open_ui")
        self.Track_controller_hw_open_ui = QtWidgets.QPushButton(self.centralwidget)
        self.Track_controller_hw_open_ui.setGeometry(QtCore.QRect(10, 130, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Track_controller_hw_open_ui.setFont(font)
        self.Track_controller_hw_open_ui.setObjectName("Track_controller_hw_open_ui")
        self.Track_model_open_ui = QtWidgets.QPushButton(self.centralwidget)
        self.Track_model_open_ui.setGeometry(QtCore.QRect(10, 270, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Track_model_open_ui.setFont(font)
        self.Track_model_open_ui.setObjectName("Track_model_open_ui")
        self.train_controller_open_ui = QtWidgets.QPushButton(self.centralwidget)
        self.train_controller_open_ui.setGeometry(QtCore.QRect(10, 340, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.train_controller_open_ui.setFont(font)
        self.train_controller_open_ui.setObjectName("train_controller_open_ui")
        self.train_model_open_ui_2 = QtWidgets.QPushButton(self.centralwidget)
        self.train_model_open_ui_2.setGeometry(QtCore.QRect(10, 410, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.train_model_open_ui_2.setFont(font)
        self.train_model_open_ui_2.setObjectName("train_model_open_ui_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        Gui_of_guis.setCentralWidget(self.centralwidget)

        self.retranslateUi(Gui_of_guis)
        QtCore.QMetaObject.connectSlotsByName(Gui_of_guis)

    def retranslateUi(self, Gui_of_guis):
        _translate = QtCore.QCoreApplication.translate
        Gui_of_guis.setWindowTitle(_translate("Gui_of_guis", "MainWindow"))
        self.CTC_open_Ui.setText(_translate("Gui_of_guis", "CTC"))
        self.Track_controller_sw_open_ui.setText(_translate("Gui_of_guis", "Track Controller - HW"))
        self.Track_controller_hw_open_ui.setText(_translate("Gui_of_guis", "Track Controller - SW"))
        self.Track_model_open_ui.setText(_translate("Gui_of_guis", "Track Model"))
        self.train_controller_open_ui.setText(_translate("Gui_of_guis", "Train Model"))
        self.train_model_open_ui_2.setText(_translate("Gui_of_guis", "Train Controller"))
        self.label.setText(_translate("Gui_of_guis", "Planes Over Trains #5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Gui_of_guis = QtWidgets.QMainWindow()
    ui = Ui_Gui_of_guis()
    ui.setupUi(Gui_of_guis)
    Gui_of_guis.show()
    sys.exit(app.exec_())
