# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'train_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
from track_model import TrackModel
from PyQt5.QtWidgets import *
from PyQt5 import uic
from PyQt5.QtCore import *
from PyQt5.QtGui import *

class Ui_Track_Model_Train(object):
    def setpUi(self, Track_Model_Train):
        Track_Model_Train.setObjectName("Track_Model_Train")
        Track_Model_Train.resize(782, 594)
        self.centralwidget = QtWidgets.QWidget(Track_Model_Train)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 0, 781, 51))
        self.title.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"border: 3px solid black;")
        self.title.setObjectName("title")
        self.clock = QtWidgets.QLabel(self.centralwidget)
        self.clock.setGeometry(QtCore.QRect(490, 10, 81, 31))
        self.clock.setStyleSheet("border: 1px solid black;\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.clock.setObjectName("clock")

#----- LABELS -----#

        self.rail_cross_label = QtWidgets.QLabel(self.centralwidget)
        self.rail_cross_label.setGeometry(QtCore.QRect(10, 240, 131, 31))
        self.rail_cross_label.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.rail_cross_label.setObjectName("rail_cross_label")
        self.curr_block_label = QtWidgets.QLabel(self.centralwidget)
        self.curr_block_label.setGeometry(QtCore.QRect(10, 200, 131, 31))
        self.curr_block_label.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.curr_block_label.setObjectName("curr_block_label")
        self.tr_clr_label = QtWidgets.QLabel(self.centralwidget)
        self.tr_clr_label.setGeometry(QtCore.QRect(10, 160, 131, 31))
        self.tr_clr_label.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.tr_clr_label.setObjectName("tr_clr_label")
        self.swpos_label = QtWidgets.QLabel(self.centralwidget)
        self.swpos_label.setGeometry(QtCore.QRect(10, 120, 131, 31))
        self.swpos_label.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.swpos_label.setObjectName("swpos_label")
        self.cmd_spd_label = QtWidgets.QLabel(self.centralwidget)
        self.cmd_spd_label.setGeometry(QtCore.QRect(10, 80, 131, 31))
        self.cmd_spd_label.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.cmd_spd_label.setObjectName("cmd_spd_label")

#----- VALUES -----#

        self.railway_crossing_train = QtWidgets.QLabel(self.centralwidget)
        self.railway_crossing_train.setGeometry(QtCore.QRect(160, 240, 51, 31))
        self.railway_crossing_train.setStyleSheet("background-color: rgb(225, 0, 0);\n"
"border: 1px solid black;\n""color: white;")
        self.railway_crossing_train.setText("NO")
        self.railway_crossing_train.setObjectName("railway_crossing_train")

        self.current_block_train = QtWidgets.QLabel(self.centralwidget)
        self.current_block_train.setGeometry(QtCore.QRect(160, 200, 51, 31))
        self.current_block_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.current_block_train.setText("A3")
        self.current_block_train.setObjectName("current_block_train")

        self.track_color_train = QtWidgets.QLabel(self.centralwidget)
        self.track_color_train.setGeometry(QtCore.QRect(160, 160, 51, 31))
        self.track_color_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.track_color_train.setText("BLUE")
        self.track_color_train.setObjectName("track_color_train")

        self.switch_position_train = QtWidgets.QLabel(self.centralwidget)
        self.switch_position_train.setGeometry(QtCore.QRect(160, 120, 51, 31))
        self.switch_position_train.setStyleSheet("background-color: rgb(225, 0, 0);\n"
"border: 1px solid black;\n""color:white;")
        self.switch_position_train.setText("NO")
        self.switch_position_train.setObjectName("switch_position_train")

        self.commanded_speed_train = QtWidgets.QLabel(self.centralwidget)
        self.commanded_speed_train.setGeometry(QtCore.QRect(160, 80, 51, 31))
        self.commanded_speed_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.commanded_speed_train.setText("50")
        self.commanded_speed_train.setObjectName("commanded_speed_train")

        self.psger_count_label = QtWidgets.QLabel(self.centralwidget)
        self.psger_count_label.setGeometry(QtCore.QRect(580, 240, 131, 31))
        self.psger_count_label.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.psger_count_label.setObjectName("psger_count_label")
        self.undr_label = QtWidgets.QLabel(self.centralwidget)
        self.undr_label.setGeometry(QtCore.QRect(580, 200, 131, 31))
        self.undr_label.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.undr_label.setObjectName("undr_label")
        self.xing_light_label = QtWidgets.QLabel(self.centralwidget)
        self.xing_light_label.setGeometry(QtCore.QRect(580, 160, 131, 31))
        self.xing_light_label.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.xing_light_label.setObjectName("xing_light_label")
        self.auth_label = QtWidgets.QLabel(self.centralwidget)
        self.auth_label.setGeometry(QtCore.QRect(580, 120, 131, 31))
        self.auth_label.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.auth_label.setObjectName("auth_label")
        self.ac_vel_label = QtWidgets.QLabel(self.centralwidget)
        self.ac_vel_label.setGeometry(QtCore.QRect(580, 80, 131, 31))
        self.ac_vel_label.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.ac_vel_label.setObjectName("ac_vel_label")

        self.passenger_count_train = QtWidgets.QLabel(self.centralwidget)
        self.passenger_count_train.setGeometry(QtCore.QRect(730, 240, 51, 31))
        self.passenger_count_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.passenger_count_train.setText("83")
        self.passenger_count_train.setObjectName("passenger_count_train")
        self.underground_train = QtWidgets.QLabel(self.centralwidget)
        self.underground_train.setGeometry(QtCore.QRect(730, 200, 51, 31))
        self.underground_train.setStyleSheet("background-color: rgb(225, 0, 0);\n"
"border: 1px solid black;\n""color:white;")
        self.underground_train.setText("NO")
        self.underground_train.setObjectName("underground_train")

        self.xing_lights_train = QtWidgets.QLabel(self.centralwidget)
        self.xing_lights_train.setGeometry(QtCore.QRect(730, 160, 51, 31))
        self.xing_lights_train.setStyleSheet("background-color: rgb(225, 0, 0);\n"
"border: 1px solid black;\n""color:white;")
        self.xing_lights_train.setText("NO")
        self.xing_lights_train.setObjectName("xing_lights_train")

        self.authority_train = QtWidgets.QLabel(self.centralwidget)
        self.authority_train.setGeometry(QtCore.QRect(730, 120, 51, 31))
        self.authority_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.authority_train.setText("1148.29")
        self.authority_train.setObjectName("authority_train")
        self.actual_velocity_train = QtWidgets.QLabel(self.centralwidget)
        self.actual_velocity_train.setGeometry(QtCore.QRect(730, 80, 51, 31))
        self.actual_velocity_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.actual_velocity_train.setText("49.6")
        self.actual_velocity_train.setObjectName("actual_velocity_train")
        self.engine_failure_label_train = QtWidgets.QLabel(self.centralwidget)
        self.engine_failure_label_train.setGeometry(QtCore.QRect(7, 400, 131, 31))
        self.engine_failure_label_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.engine_failure_label_train.setObjectName("engine_failure_label_train")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-3, 290, 781, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.power_failure_label_train = QtWidgets.QLabel(self.centralwidget)
        self.power_failure_label_train.setGeometry(QtCore.QRect(7, 440, 131, 31))
        self.power_failure_label_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.power_failure_label_train.setObjectName("power_failure_label_train")
        self.engine_failure_train = QtWidgets.QLabel(self.centralwidget)
        self.engine_failure_train.setGeometry(QtCore.QRect(157, 400, 51, 31))
        self.engine_failure_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"background-color: rgb(170, 0, 0);\n"
"border: 1px solid black;\n"
"color: white")
        self.engine_failure_train.setAlignment(QtCore.Qt.AlignCenter)
        self.engine_failure_train.setObjectName("engine_failure_train")
        self.brake_failure_label_train = QtWidgets.QLabel(self.centralwidget)
        self.brake_failure_label_train.setGeometry(QtCore.QRect(7, 360, 131, 31))
        self.brake_failure_label_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.brake_failure_label_train.setObjectName("brake_failure_label_train")
        self.broken_rail_train = QtWidgets.QLabel(self.centralwidget)
        self.broken_rail_train.setGeometry(QtCore.QRect(157, 520, 51, 31))
        self.broken_rail_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"background-color: rgb(170, 0, 0);\n"
"border: 1px solid black;\n"
"color: white")
        self.broken_rail_train.setAlignment(QtCore.Qt.AlignCenter)
        self.broken_rail_train.setObjectName("broken_rail_train")
        self.circuit_failure_train = QtWidgets.QLabel(self.centralwidget)
        self.circuit_failure_train.setGeometry(QtCore.QRect(157, 480, 51, 31))
        self.circuit_failure_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"background-color: rgb(170, 0, 0);\n"
"border: 1px solid black;\n"
"color: white")
        self.circuit_failure_train.setAlignment(QtCore.Qt.AlignCenter)
        self.circuit_failure_train.setObjectName("circuit_failure_train")
        self.brake_failure_train = QtWidgets.QLabel(self.centralwidget)
        self.brake_failure_train.setGeometry(QtCore.QRect(157, 360, 51, 31))
        self.brake_failure_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"background-color: rgb(170, 0, 0);\n"
"border: 1px solid black;\n"
"color: white")
        self.brake_failure_train.setAlignment(QtCore.Qt.AlignCenter)
        self.brake_failure_train.setObjectName("brake_failure_train")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(350, 300, 20, 261))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.failure_title_train = QtWidgets.QLabel(self.centralwidget)
        self.failure_title_train.setGeometry(QtCore.QRect(-3, 300, 361, 51))
        self.failure_title_train.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"border: 3px solid black;")
        self.failure_title_train.setObjectName("failure_title_train")
        self.broken_rail_label_train = QtWidgets.QLabel(self.centralwidget)
        self.broken_rail_label_train.setGeometry(QtCore.QRect(7, 520, 131, 31))
        self.broken_rail_label_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.broken_rail_label_train.setObjectName("broken_rail_label_train")
        self.power_failiure_train = QtWidgets.QLabel(self.centralwidget)
        self.power_failiure_train.setGeometry(QtCore.QRect(157, 440, 51, 31))
        self.power_failiure_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"background-color: rgb(170, 0, 0);\n"
"border: 1px solid black;\n"
"color: white")
        self.power_failiure_train.setAlignment(QtCore.Qt.AlignCenter)
        self.power_failiure_train.setObjectName("power_failiure_train")
        self.circuit_failure_label_train = QtWidgets.QLabel(self.centralwidget)
        self.circuit_failure_label_train.setGeometry(QtCore.QRect(7, 480, 131, 31))
        self.circuit_failure_label_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.circuit_failure_label_train.setObjectName("circuit_failure_label_train")
        self.passenger_title = QtWidgets.QLabel(self.centralwidget)
        self.passenger_title.setGeometry(QtCore.QRect(360, 300, 421, 51))
        self.passenger_title.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"border: 3px solid black;")
        self.passenger_title.setObjectName("passenger_title")
        self.onboarding_label_train = QtWidgets.QLabel(self.centralwidget)
        self.onboarding_label_train.setGeometry(QtCore.QRect(380, 390, 131, 41))
        self.onboarding_label_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.onboarding_label_train.setAlignment(QtCore.Qt.AlignCenter)
        self.onboarding_label_train.setObjectName("onboarding_label_train")
        self.offboarding_label_train = QtWidgets.QLabel(self.centralwidget)
        self.offboarding_label_train.setGeometry(QtCore.QRect(380, 480, 131, 41))
        self.offboarding_label_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.offboarding_label_train.setAlignment(QtCore.Qt.AlignCenter)
        self.offboarding_label_train.setObjectName("offboarding_label_train")
        self.onboarding_train = QtWidgets.QLabel(self.centralwidget)
        self.onboarding_train.setGeometry(QtCore.QRect(600, 390, 51, 41))
        self.onboarding_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.onboarding_train.setText("")
        self.onboarding_train.setObjectName("onboarding_train")
        self.onboarding_double = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.onboarding_double.setGeometry(QtCore.QRect(600,390,51,41))


        self.offboarding_train = QtWidgets.QLabel(self.centralwidget)
        self.offboarding_train.setGeometry(QtCore.QRect(600, 480, 51, 41))
        self.offboarding_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.offboarding_train.setText("")
        self.offboarding_train.setObjectName("offboarding_train")
        self.offboarding_double = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.offboarding_double.setGeometry(QtCore.QRect(600,480,51,41))

        self.onboarding_double.valueChanged.connect(self.update_passenger_count)
        self.offboarding_double.valueChanged.connect(self.update_passenger_count)
        self.pass_count = 100
        self.update_passenger_count()


        self.temp_control_label_train = QtWidgets.QLabel(self.centralwidget)
        self.temp_control_label_train.setGeometry(QtCore.QRect(330, 80, 131, 31))
        self.temp_control_label_train.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border: 1px solid black;")
        self.temp_control_label_train.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_control_label_train.setObjectName("temp_control_label_train")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(360, 120, 71, 22))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox.setValue(70)
        Track_Model_Train.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Track_Model_Train)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 18))
        self.menubar.setObjectName("menubar")
        Track_Model_Train.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Track_Model_Train)
        self.statusbar.setObjectName("statusbar")
        Track_Model_Train.setStatusBar(self.statusbar)

        self.retranslateUi(Track_Model_Train)
        QtCore.QMetaObject.connectSlotsByName(Track_Model_Train)

    def retranslateUi(self, Track_Model_Train):
        _translate = QtCore.QCoreApplication.translate
        Track_Model_Train.setWindowTitle(_translate("Track_Model_Train", "MainWindow"))
        self.title.setText(_translate("Track_Model_Train", "Train 7"))
        self.clock.setText(_translate("Track_Model_Train", "13:56:54"))
        self.rail_cross_label.setText(_translate("Track_Model_Train", "Railway Crossing"))
        self.curr_block_label.setText(_translate("Track_Model_Train", "Current Block"))
        self.tr_clr_label.setText(_translate("Track_Model_Train", "Track Color"))
        self.swpos_label.setText(_translate("Track_Model_Train", "Switch Position"))
        self.cmd_spd_label.setText(_translate("Track_Model_Train", "Commanded Speed (mph)"))
        self.psger_count_label.setText(_translate("Track_Model_Train", "Passenger Count"))
        self.undr_label.setText(_translate("Track_Model_Train", "Underground"))
        self.xing_light_label.setText(_translate("Track_Model_Train", "Crossing Lights"))
        self.auth_label.setText(_translate("Track_Model_Train", "Authority (ft)"))
        self.ac_vel_label.setText(_translate("Track_Model_Train", "Actual Velocity (mph)"))
        self.engine_failure_label_train.setText(_translate("Track_Model_Train", "Engine Failure"))
        self.power_failure_label_train.setText(_translate("Track_Model_Train", "Power Failure"))
        self.engine_failure_train.setText(_translate("Track_Model_Train", "OFF"))
        self.brake_failure_label_train.setText(_translate("Track_Model_Train", "Brake Failure"))
        self.broken_rail_train.setText(_translate("Track_Model_Train", "OFF"))
        self.circuit_failure_train.setText(_translate("Track_Model_Train", "OFF"))
        self.brake_failure_train.setText(_translate("Track_Model_Train", "OFF"))
        self.failure_title_train.setText(_translate("Track_Model_Train", "Failure Modes"))
        self.broken_rail_label_train.setText(_translate("Track_Model_Train", "Broken Rail"))
        self.power_failiure_train.setText(_translate("Track_Model_Train", "OFF"))
        self.circuit_failure_label_train.setText(_translate("Track_Model_Train", "Circuit Failure"))
        self.passenger_title.setText(_translate("Track_Model_Train", "Passengers Boarding"))
        self.onboarding_label_train.setText(_translate("Track_Model_Train", "Onboarding"))
        self.offboarding_label_train.setText(_translate("Track_Model_Train", "Offboarding"))
        self.temp_control_label_train.setText(_translate("Track_Model_Train", "Temperature Control"))

    def update_passenger_count(self):
            onboarding = self.onboarding_double.value()
            offboarding = self.offboarding_double.value()
            self.pass_count_2 = self.pass_count + onboarding - offboarding
            self.passenger_count_train.setText(str(self.pass_count_2))





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Track_Model_Train = QtWidgets.QMainWindow()
    ui = Ui_Track_Model_Train()
    ui.setpUi(Track_Model_Train)

    Track_Model_Train.show()
    sys.exit(app.exec_())
